---
default:
  noarch: false
  version: "1.0.0"
  vendor: "PowerPackageTool"
  packager: "opsx@service.alibaba.com"
  license: "Apache2"
  group: "ppt"
  url: https://opsx.alibaba.com/
  description: |
    description for this package.
  setting:
    script:
      build: hack/build.sh

distribution:
  centos6.x86_64.placeholder: true
  centos7.x86_64.placeholder: true
  ubuntu16.amd64.placeholder: true
  ubuntu18.amd64.palceholder: true
